//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaPlayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(View all)")]
        public string ViewAllText {
            get {
                return ((string)(this["ViewAllText"]));
            }
            set {
                this["ViewAllText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RootFolderFileExceptions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RootFolderFileExceptions"]));
            }
            set {
                this["RootFolderFileExceptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RootFolderDirectoryExceptions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RootFolderDirectoryExceptions"]));
            }
            set {
                this["RootFolderDirectoryExceptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StretchMediaPlayer {
            get {
                return ((bool)(this["StretchMediaPlayer"]));
            }
            set {
                this["StretchMediaPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double Volume {
            get {
                return ((double)(this["Volume"]));
            }
            set {
                this["Volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowTimeRemaining {
            get {
                return ((bool)(this["ShowTimeRemaining"]));
            }
            set {
                this["ShowTimeRemaining"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoveMediaItemFromNowPlayingOnFinish {
            get {
                return ((bool)(this["RemoveMediaItemFromNowPlayingOnFinish"]));
            }
            set {
                this["RemoveMediaItemFromNowPlayingOnFinish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OrganiseMissingMediaItems {
            get {
                return ((bool)(this["OrganiseMissingMediaItems"]));
            }
            set {
                this["OrganiseMissingMediaItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MSSQLSERVER")]
        public string SqlServerServiceName {
            get {
                return ((string)(this["SqlServerServiceName"]));
            }
            set {
                this["SqlServerServiceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TorrentSearchPrefix {
            get {
                return ((string)(this["TorrentSearchPrefix"]));
            }
            set {
                this["TorrentSearchPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TorrentSearchSuffix {
            get {
                return ((string)(this["TorrentSearchSuffix"]));
            }
            set {
                this["TorrentSearchSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TorrentSearchUrl {
            get {
                return ((string)(this["TorrentSearchUrl"]));
            }
            set {
                this["TorrentSearchUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TorrentSearchSpaceCharacter {
            get {
                return ((string)(this["TorrentSearchSpaceCharacter"]));
            }
            set {
                this["TorrentSearchSpaceCharacter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PauseOnLock {
            get {
                return ((bool)(this["PauseOnLock"]));
            }
            set {
                this["PauseOnLock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UnpauseOnUnlock {
            get {
                return ((bool)(this["UnpauseOnUnlock"]));
            }
            set {
                this["UnpauseOnUnlock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MinimizeOnLock {
            get {
                return ((bool)(this["MinimizeOnLock"]));
            }
            set {
                this["MinimizeOnLock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RestoreOnUnlock {
            get {
                return ((bool)(this["RestoreOnUnlock"]));
            }
            set {
                this["RestoreOnUnlock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ExportDirectories {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ExportDirectories"]));
            }
            set {
                this["ExportDirectories"] = value;
            }
        }
    }
}
