//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wedding.eVite.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wedding.eVite.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;John &amp;amp; Lizzie are getting married&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            background-color: #f0f0f0;
        ///            margin: 0;
        ///            padding: 0;
        ///            font-family: Georgia;
        ///        }
        ///
        ///        @media screen and (-webkit-min-device-pixel-ratio: 3.0) and (max-width: 1080px), only screen and (max-width: 480px) {
        ///            /* mobile-specific CSS styles go here */
        ///            table[class=contentTable] {
        ///                width: 320px !impo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GiftWebsiteEmail {
            get {
                return ResourceManager.GetString("GiftWebsiteEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;John &amp;amp; Lizzie are getting married&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            background-color: #f0f0f0;
        ///            margin: 0;
        ///            padding: 0;
        ///            font-family: Georgia;
        ///        }
        ///
        ///        @media screen and (-webkit-min-device-pixel-ratio: 3.0) and (max-width: 1080px), only screen and (max-width: 480px) {
        ///            /* mobile-specific CSS styles go here */
        ///            table[class=contentTable] {
        ///                width: 320px !impo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InviteEmail {
            get {
                return ResourceManager.GetString("InviteEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;John &amp;amp; Lizzie are getting married&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            background-color: #f0f0f0;
        ///            margin: 0;
        ///            padding: 0;
        ///            font-family: Georgia;
        ///        }
        ///
        ///        @media screen and (-webkit-min-device-pixel-ratio: 3.0) and (max-width: 1080px), only screen and (max-width: 480px) {
        ///            /* mobile-specific CSS styles go here */
        ///            table[class=contentTable] {
        ///                width: 320px !impo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InviteEmailReceptionOnly {
            get {
                return ResourceManager.GetString("InviteEmailReceptionOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;John &amp;amp; Lizzie are getting married&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            background-color: #f0f0f0;
        ///            margin: 0;
        ///            padding: 0;
        ///            font-family: Georgia;
        ///        }
        ///
        ///        @media screen and (-webkit-min-device-pixel-ratio: 3.0) and (max-width: 1080px), only screen and (max-width: 480px) {
        ///            /* mobile-specific CSS styles go here */
        ///            table[class=contentTable] {
        ///                width: 320px !impo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MessageFromInvite {
            get {
                return ResourceManager.GetString("MessageFromInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;John &amp;amp; Lizzie are getting married&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            background-color: #f0f0f0;
        ///            margin: 0;
        ///            padding: 0;
        ///            font-family: Georgia;
        ///        }
        ///
        ///        @media screen and (-webkit-min-device-pixel-ratio: 3.0) and (max-width: 1080px), only screen and (max-width: 480px) {
        ///            /* mobile-specific CSS styles go here */
        ///            table[class=contentTable] {
        ///                width: 320px !impo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MessageToInvite {
            get {
                return ResourceManager.GetString("MessageToInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;John &amp;amp; Lizzie are getting married&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            background-color: #f0f0f0;
        ///            margin: 0;
        ///            padding: 0;
        ///            font-family: Georgia;
        ///        }
        ///
        ///        @media screen and (-webkit-min-device-pixel-ratio: 3.0) and (max-width: 1080px), only screen and (max-width: 480px) {
        ///            /* mobile-specific CSS styles go here */
        ///            table[class=contentTable] {
        ///                width: 320px !impo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateInviteEmail {
            get {
                return ResourceManager.GetString("UpdateInviteEmail", resourceCulture);
            }
        }
    }
}
